//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Contact Page</summary>
	[PublishedModel("contactPage")]
	public partial class ContactPage : PublishedContentModel, IHomePage
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "contactPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ContactPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ContactPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Contact Company1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactCompany1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactCompany1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactCompany1");

		///<summary>
		/// Contact Company2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactCompany2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactCompany2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactCompany2");

		///<summary>
		/// Contact Company3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactCompany3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactCompany3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactCompany3");

		///<summary>
		/// Contact Company4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactCompany4")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactCompany4 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactCompany4");

		///<summary>
		/// Contact Company5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactCompany5")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactCompany5 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactCompany5");

		///<summary>
		/// Contact Company6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactCompany6")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactCompany6 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactCompany6");

		///<summary>
		/// Contact Map Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactMapImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ContactMapImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "contactMapImage");

		///<summary>
		/// About - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutHeadline")]
		public virtual string AboutHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetAboutHeadline(this, _publishedValueFallback);

		///<summary>
		/// About - Quote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutQuote")]
		public virtual string AboutQuote => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetAboutQuote(this, _publishedValueFallback);

		///<summary>
		/// About - Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSectionTitle")]
		public virtual string AboutSectionTitle => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetAboutSectionTitle(this, _publishedValueFallback);

		///<summary>
		/// About - Signature
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSignature")]
		public virtual string AboutSignature => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetAboutSignature(this, _publishedValueFallback);

		///<summary>
		/// About - Signature Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutSignatureImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutSignatureImage => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetAboutSignatureImage(this, _publishedValueFallback);

		///<summary>
		/// About - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutText")]
		public virtual string AboutText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetAboutText(this, _publishedValueFallback);

		///<summary>
		/// Company - ImageFive
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyImageFive")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CompanyImageFive => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetCompanyImageFive(this, _publishedValueFallback);

		///<summary>
		/// Company - ImageFour
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyImageFour")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CompanyImageFour => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetCompanyImageFour(this, _publishedValueFallback);

		///<summary>
		/// Company - ImageOne
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyImageOne")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CompanyImageOne => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetCompanyImageOne(this, _publishedValueFallback);

		///<summary>
		/// Company - ImageSix
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyImageSix")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CompanyImageSix => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetCompanyImageSix(this, _publishedValueFallback);

		///<summary>
		/// Company - ImageThree
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyImageThree")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CompanyImageThree => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetCompanyImageThree(this, _publishedValueFallback);

		///<summary>
		/// Company - ImageTwo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("companyImageTwo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CompanyImageTwo => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetCompanyImageTwo(this, _publishedValueFallback);

		///<summary>
		/// Hero - Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops HeroBackgroundImage => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetHeroBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Hero - Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroButtonText")]
		public virtual string HeroButtonText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetHeroButtonText(this, _publishedValueFallback);

		///<summary>
		/// Hero - Button Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroButtonUrl")]
		public virtual string HeroButtonUrl => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetHeroButtonUrl(this, _publishedValueFallback);

		///<summary>
		/// Hero - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroHeadline")]
		public virtual string HeroHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetHeroHeadline(this, _publishedValueFallback);

		///<summary>
		/// Hero - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("heroText")]
		public virtual string HeroText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetHeroText(this, _publishedValueFallback);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetPageTitle(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxFourH5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxFourH5")]
		public virtual string RecentBoxFourH5 => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxFourH5(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxFourImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxFourImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentBoxFourImg => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxFourImg(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxFourText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxFourText")]
		public virtual string RecentBoxFourText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxFourText(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxOneH5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxOneH5")]
		public virtual string RecentBoxOneH5 => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxOneH5(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxOneImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxOneImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentBoxOneImg => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxOneImg(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxOneText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxOneText")]
		public virtual string RecentBoxOneText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxOneText(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxThreeH5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxThreeH5")]
		public virtual string RecentBoxThreeH5 => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxThreeH5(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxThreeImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxThreeImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentBoxThreeImg => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxThreeImg(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxThreeText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxThreeText")]
		public virtual string RecentBoxThreeText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxThreeText(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxTwoh5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxTwoh5")]
		public virtual string RecentBoxTwoh5 => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxTwoh5(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxTwoImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxTwoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops RecentBoxTwoImage => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxTwoImage(this, _publishedValueFallback);

		///<summary>
		/// Recent - BoxTwoText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentBoxTwoText")]
		public virtual string RecentBoxTwoText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentBoxTwoText(this, _publishedValueFallback);

		///<summary>
		/// Recent - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentHeadline")]
		public virtual string RecentHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentHeadline(this, _publishedValueFallback);

		///<summary>
		/// Recent - SectionTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("recentSectionTitle")]
		public virtual string RecentSectionTitle => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetRecentSectionTitle(this, _publishedValueFallback);

		///<summary>
		/// Services Section Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesSectionHeadline")]
		public virtual string ServicesSectionHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetServicesSectionHeadline(this, _publishedValueFallback);

		///<summary>
		/// Services Section Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servicesSectionTitle")]
		public virtual string ServicesSectionTitle => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetServicesSectionTitle(this, _publishedValueFallback);

		///<summary>
		/// Story - BackgroundDotImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyBackgroundDotImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops StoryBackgroundDotImage => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetStoryBackgroundDotImage(this, _publishedValueFallback);

		///<summary>
		/// Story - ButtonText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyButtonText")]
		public virtual string StoryButtonText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetStoryButtonText(this, _publishedValueFallback);

		///<summary>
		/// Story - ButtonUrl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyButtonUrl")]
		public virtual string StoryButtonUrl => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetStoryButtonUrl(this, _publishedValueFallback);

		///<summary>
		/// Story - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyHeadline")]
		public virtual string StoryHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetStoryHeadline(this, _publishedValueFallback);

		///<summary>
		/// Story - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops StoryImage => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetStoryImage(this, _publishedValueFallback);

		///<summary>
		/// Story - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storyText")]
		public virtual string StoryText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetStoryText(this, _publishedValueFallback);

		///<summary>
		/// Success - boxOneNumber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBoxOneNumber")]
		public virtual string SuccessBoxOneNumber => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessBoxOneNumber(this, _publishedValueFallback);

		///<summary>
		/// Success - BoxOneText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBoxOneText")]
		public virtual string SuccessBoxOneText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessBoxOneText(this, _publishedValueFallback);

		///<summary>
		/// Success - BoxThreeNumber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBoxThreeNumber")]
		public virtual string SuccessBoxThreeNumber => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessBoxThreeNumber(this, _publishedValueFallback);

		///<summary>
		/// Success - BoxThreeText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBoxThreeText")]
		public virtual string SuccessBoxThreeText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessBoxThreeText(this, _publishedValueFallback);

		///<summary>
		/// Success - BoxTwoNumber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBoxTwoNumber")]
		public virtual string SuccessBoxTwoNumber => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessBoxTwoNumber(this, _publishedValueFallback);

		///<summary>
		/// Success - BoxTwoText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successBoxTwoText")]
		public virtual string SuccessBoxTwoText => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessBoxTwoText(this, _publishedValueFallback);

		///<summary>
		/// Success - dotbackgroundImg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successDotbackgroundImg")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SuccessDotbackgroundImg => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessDotbackgroundImg(this, _publishedValueFallback);

		///<summary>
		/// Success - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successHeadline")]
		public virtual string SuccessHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessHeadline(this, _publishedValueFallback);

		///<summary>
		/// Success - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SuccessImage => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessImage(this, _publishedValueFallback);

		///<summary>
		/// Success - SectionTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("successSectionTitle")]
		public virtual string SuccessSectionTitle => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetSuccessSectionTitle(this, _publishedValueFallback);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Cms.Web.Common.PublishedModels.HomePage.GetTitle(this, _publishedValueFallback);
	}
}
